apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-news-feeder
  namespace: ai-news

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-news-feeder

  template:
    metadata:
      labels:
        app: ai-news-feeder

    spec:
      containers:
      - name: ai-news-feeder

        image: 410386583102.dkr.ecr.ap-south-1.amazonaws.com/ai-news-feeder:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-secret
              key: GEMINI_API_KEY
